version: "3.8"

services:
  spring_api:
    image: springci/spring-boot-ci-image
      container_name: spring_api
      depends_on:
        - postgres
      working_dir:
      volumes:
      environment:
        - SPRING_DATASOURCE_URL=
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: 'postgres:13.1-alpine'
      container_name: postgres
      working_dir:
      volumes:
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin